-- SmartAgri Supabase schema for UI, database, and authenticated ESP32 hardware integration.
-- Hardware scope: ESP32, soil moisture sensor, water detection sensor, relay, water pump.
-- Includes user-authenticated UI routes and device-authenticated ESP32 control routes.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  username text not null unique,
  password text not null,
  address text default '',
  phone_number text default '',
  role text not null default 'farmer' check (role in ('farmer','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.thresholds (
  user_id bigint primary key references public.users(id) on delete cascade,
  dry_threshold numeric(5,2) not null default 30 check (dry_threshold between 0 and 100),
  wet_threshold numeric(5,2) not null default 70 check (wet_threshold between 0 and 100),
  auto_irrigation boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint valid_threshold_order check (dry_threshold < wet_threshold)
);

create table if not exists public.pump_state (
  user_id bigint primary key references public.users(id) on delete cascade,
  is_on boolean not null default false, -- desired pump state/command
  actual_is_on boolean not null default false, -- last state reported by physical ESP32; simulation mirrors is_on in app logic
  device_last_seen_at timestamptz,
  device_online boolean not null default false,
  mode text not null default 'manual' check (mode in ('manual','auto')),
  updated_at timestamptz not null default now()
);

-- Safe additive upgrade for databases created from the earlier UI-only schema.
alter table public.pump_state add column if not exists actual_is_on boolean not null default false;
alter table public.pump_state add column if not exists device_last_seen_at timestamptz;
alter table public.pump_state add column if not exists device_online boolean not null default false;

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  moisture_percent numeric(5,2) not null check (moisture_percent between 0 and 100),
  soil_sensor_raw integer check (soil_sensor_raw is null or soil_sensor_raw between 0 and 4095),
  water_detected boolean not null,
  source text not null default 'simulation' check (source in ('simulation','esp32')),
  created_at timestamptz not null default now()
);
create index if not exists sensor_readings_user_created_idx on public.sensor_readings(user_id,created_at desc);

create table if not exists public.irrigation_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  action text not null check (action in ('on','off')),
  trigger_type text not null check (trigger_type in ('manual','auto','safety')),
  moisture_at_trigger numeric(5,2) check (moisture_at_trigger is null or moisture_at_trigger between 0 and 100),
  water_detected boolean,
  created_at timestamptz not null default now()
);
create index if not exists irrigation_logs_user_created_idx on public.irrigation_logs(user_id,created_at desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'system' check (type in ('system','soil_low','soil_normal','water_detected','no_water','pump_on','pump_off')),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);

create or replace function public.update_modified_column()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_updated_at on public.users;
create trigger users_updated_at before update on public.users for each row execute function public.update_modified_column();
drop trigger if exists thresholds_updated_at on public.thresholds;
create trigger thresholds_updated_at before update on public.thresholds for each row execute function public.update_modified_column();
drop trigger if exists pump_state_updated_at on public.pump_state;
create trigger pump_state_updated_at before update on public.pump_state for each row execute function public.update_modified_column();

create or replace function public.create_default_user_settings()
returns trigger language plpgsql as $$
begin
  insert into public.thresholds(user_id,dry_threshold,wet_threshold,auto_irrigation) values(new.id,30,70,true);
  insert into public.pump_state(user_id,is_on,mode) values(new.id,false,'manual');
  return new;
end;
$$;

drop trigger if exists create_user_defaults on public.users;
create trigger create_user_defaults after insert on public.users for each row execute function public.create_default_user_settings();

-- Backfill settings for accounts created before the default trigger was installed.
insert into public.thresholds(user_id,dry_threshold,wet_threshold,auto_irrigation)
select id,30,70,true from public.users on conflict (user_id) do nothing;
insert into public.pump_state(user_id,is_on,actual_is_on,device_online,mode)
select id,false,false,false,'manual' from public.users on conflict (user_id) do nothing;

alter table public.users enable row level security;
alter table public.thresholds enable row level security;
alter table public.pump_state enable row level security;
alter table public.sensor_readings enable row level security;
alter table public.irrigation_logs enable row level security;
alter table public.notifications enable row level security;
